id = "twig"
name = "Twig"
version = "0.0.1"
schema_version = 1
authors = ["Peter Oesteritz <peter.oesteritz@evernow.io>"]
description = "Twig extension for Zed"
repository = "https://github.com/evernow-io/zed-twig"
languages = ["languages/twig"]

[grammars.twig]
repository = "https://github.com/gbprod/tree-sitter-twig"
commit = "eaf80e6af969e25993576477a9dbdba3e48c1305"
